name: blue_print_pos
description: Helper to use bluetooth print in Android and iOS
version: 0.0.1
author: Andri Yoga Nur Pratama<andriyoga.np@gmail.com>

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  # Handler bluetooth for Android
  blue_thermal_printer: ^1.1.3
  # Utilities for generate ByteBuffer
  esc_pos_utils_plus: ^2.0.1+3
  # Framewework
  flutter:
    sdk: flutter
  # Handler bluetooth for iOS
  flutter_blue: ^0.8.0
  # Generate qr image painter
  qr_flutter: ^4.0.0
  # Convert image to ByteBuffer
  webcontent_converter: ^0.0.6+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.ayeee.blue_print_pos
        pluginClass: BluePrintPosPlugin
      ios:
        pluginClass: BluePrintPosPlugin
